version: '3.8'
services:
  relaydb:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - .pg:/var/lib/postgresql/data

  nodejs_app:
    build: .  # Build the Node.js app using the Dockerfile in the current directory
    ports:
      - "3000:3000"  # Map your app's port to a host port if needed
    depends_on:
      - relaydb  # Ensure that the PostgreSQL container is started before the Node.js app
    env_file:
      - .env  # You can specify environment variables here if needed
